import type { Caso, Organizacion, Usuario, Sesion, Informe, LogEnvio, FacturaOrganizacion, PagoMedico } from '@prisma/client'
export type EstadoCaso = 'recibido' | 'en_revision' | 'informe_en_validacion' | 'entregado'
export type PrioridadCaso = 'normal' | 'urgente'
export type Rol = 'cliente' | 'medico' | 'backoffice'
export type TipoOrganizacion = 'isapre' | 'compin' | 'empresa' | 'seguro' | 'subcontratista'
export type EstadoSesion = 'agendada' | 'en_curso' | 'realizada' | 'incumplida_medico' | 'incumplida_evaluado' | 'reprogramada' | 'cancelada'
export type FirmaProveedor = 'firmaweb' | 'sovos' | 'otro'
export type CanalEnvio = 'whatsapp' | 'email'
export type EstadoEnvio = 'enviado' | 'entregado' | 'leido' | 'fallido'
export type EstadoPago = 'pendiente' | 'pagado'
export type EstadoFactura = 'pendiente' | 'facturada' | 'pagada'
